# Generated by Django 3.2.3 on 2021-05-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
